Fallback consensus through lower num of signatures
ElrondNetwork/elrond-go pull request #2327
Opened 2020-09-28 14:12 UTC by SebastianMarian

2020-10-05 07:36 UTC, iulianpascalau approved these changes

2020-10-05 07:36 UTC, iulianpascalau commented on process/headerCheck/headerSignatureVerify.go
> +		minNumRequiredSignatures = core.GetPBFTFallbackThreshold(consensusSize)
Maybe add a debug print here?

2020-10-05 08:19 UTC, iulianpascalau approved these changes

2020-10-06 05:36 UTC, AdoAdoAdo requested changes

2020-10-06 09:34 UTC, SebastianMarian commented on node/node.go
> +	heartbeatHandler        *componentHandler.HeartbeatHandler
Done

2020-10-06 11:14 UTC, AdoAdoAdo approved these changes

2020-10-07 13:56 UTC, iulianpascalau approved these changes

2020-10-07 19:06 UTC, LucianMincu approved these changes
🪑 💯

2020-10-07 19:16 UTC, merged