En 7776/delegation sc first part
ElrondNetwork/elrond-go pull request #2354
Opened 2020-10-08 14:59 UTC by sasurobert

This is mostly the implementation of the delegation contract. The owner functions and some of the user functions. Will continue the rest in subsequent PRs, but will make it in smaller batches.

The related document: https://docs.google.com/document/d/1ZWiMJfP3uOyV4xwtWn3BK9QI9hEQQg_WewQZFW1A4iU/edit

2020-10-08 20:14 UTC, SebastianMarian reviewed
We need unit tests as well

2020-10-09 09:12 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	delegationMgrSCAddress   []byte
that is too long

2020-10-09 09:12 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	delegationMgrEnabled     atomic.Flag
that is too long

2020-10-09 09:12 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	enableDelegationMgrEpoch uint32
that is too long

2020-10-09 09:12 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	DelegationMgrSCConfig  config.DelegationManagerSystemSCConfig
that is too long

2020-10-09 09:13 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	DelegationMgrSCAddress []byte
that is too long

2020-10-09 09:33 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	delegationMgrSCAddress []byte
it would be too long

2020-10-09 09:45 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +// ArgsNewDelegation -
done

2020-10-09 09:45 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	DelegationMgrSCAddress []byte
it would be too long

2020-10-09 09:45 UTC, sasurobert commented on vm/systemSmartContracts/delegationManager.go
> +	mgr := &delegationManager{
done

2020-10-09 09:46 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	if !okValue {
done

2020-10-09 09:46 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		return nil, vm.ErrInvalidBaseIssuingCost
done

2020-10-09 09:48 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	err := d.eei.UseGas(d.gasCost.MetaChainSystemSCsCost.ESDTOperations)
no - but I wanted to implement gas scheduling later for these contracts. After some benchmarking

2020-10-09 09:48 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		d.eei.AddReturnMessage("not enough arguments to init delegation contract")
done

2020-10-09 09:52 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	err := d.eei.UseGas(numBlsKeys * d.gasCost.MetaChainSystemSCsCost.ESDTOperations)
done

2020-10-09 09:53 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		found := false
done

2020-10-09 09:53 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +func (d *delegation) verifiedBLSKeysAndSignature(txPubKey []byte, args [][]byte) ([][]byte, error) {
done

2020-10-09 09:53 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	err := d.eei.UseGas(uint64(len(args.Arguments)) * d.gasCost.MetaChainSystemSCsCost.ESDTOperations)
done

2020-10-09 09:54 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		return vmcommon.UserError
done

2020-10-09 09:54 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		for i, nodeData := range dStatus.NotStakedKeys {
yes. you can remove only those nodes which are not staked

2020-10-09 09:54 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	err := d.eei.UseGas(d.gasCost.MetaChainSystemSCsCost.ESDTOperations)
done

2020-10-09 09:55 UTC, SebastianMarian commented on vm/systemSmartContracts/delegation.go
> +	err := d.eei.UseGas(d.gasCost.MetaChainSystemSCsCost.ESDTOperations)
maybe it should be added a TODO here

2020-10-09 16:26 UTC, SebastianMarian commented on vm/systemSmartContracts/delegation.go
> +				return fmt.Errorf("%w, key %s already exists", vm.ErrBLSPublicKeyMismatch, hex.EncodeToString(argKey))
You can also add information about where it exists, just to differentiate between this return and the one below: ...already exists in not staked keys

2020-10-09 16:26 UTC, SebastianMarian commented on vm/systemSmartContracts/delegation.go
> +				return fmt.Errorf("%w, key %s already exists", vm.ErrBLSPublicKeyMismatch, hex.EncodeToString(argKey))
You can also add information about where it exists, just to differentiate between this return and the one above: ...already exists in staked keys

2020-10-12 09:18 UTC, BeniaminDrasovean requested changes

2020-10-12 13:12 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	d := &delegation{
done.

2020-10-12 13:12 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		return vmcommon.UserError
the only way to get here is if there is a serious issue in the protocol.

2020-10-12 13:14 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		return vmcommon.UserError
done

2020-10-12 13:14 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	return vmcommon.UserError
done

2020-10-12 13:15 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	if len(ownerAddress) == 0 {
done

2020-10-12 13:17 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		d.eei.AddReturnMessage("invalid new service fee")
done

2020-10-12 13:17 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +		d.eei.AddReturnMessage("invalid new service fee")
done

2020-10-12 13:24 UTC, BeniaminDrasovean approved these changes

2020-10-12 13:40 UTC, SebastianMarian approved these changes

2020-10-12 15:10 UTC, merged