send back gas to relayer
ElrondNetwork/elrond-go pull request #2373
Opened 2020-10-13 12:02 UTC by sasurobert

2020-10-13 15:07 UTC, bogdan-rosianu requested changes

2020-10-13 15:26 UTC, iulianpascalau commented on process/smartContract/process.go
> +) (*smartContractResult.SmartContractResult, *smartContractResult.SmartContractResult, error) {
Although this works, returning 2 consecutive elements of the same type is always prone to faults (caused by switching variables)

2020-10-13 15:26 UTC, iulianpascalau commented on process/smartContract/process.go
> +	if relayedSCR.Value.Cmp(zero) == 0 {
test relayedSCR.Value for nil?

2020-10-13 15:26 UTC, iulianpascalau commented on process/smartContract/process.go
> +) (*smartContractResult.SmartContractResult, *smartContractResult.SmartContractResult) {
same thing about multiple, same-type variables.

2020-10-13 16:36 UTC, sasurobert commented on process/smartContract/process.go
> +	err = sc.accounts.SaveAccount(userAcc)
done

2020-10-13 16:37 UTC, sasurobert commented on process/smartContract/process.go
> +		refundGasToRelayer = &smartContractResult.SmartContractResult{
done

2020-10-13 16:37 UTC, sasurobert commented on process/smartContract/process.go
> +) (*smartContractResult.SmartContractResult, *smartContractResult.SmartContractResult) {
any better idea ? :)

2020-10-13 16:42 UTC, iulianpascalau commented on process/smartContract/process.go
> +	if relayedSCR.Value.Cmp(zero) == 0 {
ok

2020-10-13 16:43 UTC, iulianpascalau approved these changes

2020-10-14 06:59 UTC, bogdan-rosianu approved these changes

2020-10-14 07:33 UTC, iulianpascalau approved these changes

2020-10-14 07:35 UTC, bogdan-rosianu approved these changes

2020-10-14 07:47 UTC, merged