Fix bad tx behaviour through tx pool cleaning
ElrondNetwork/elrond-go pull request #2374
Opened 2020-10-13 16:34 UTC by SebastianMarian

* Refactored some misleading methods name compared with their behaviour in TransactionCoordinator and PreProcess interface/implementations
* Fixed bad tx behaviour through tx pool cleaning for each processed tx at commit time

2020-10-14 10:45 UTC, sasurobert approved these changes

2020-10-14 10:50 UTC, bogdan-rosianu requested changes

2020-10-14 15:39 UTC, SebastianMarian commented on process/block/baseProcess.go
> +	err := bp.txCoordinator.RemoveTxsFromPool(body)
Done

2020-10-14 15:40 UTC, SebastianMarian commented on process/block/preprocess/basePreProcess.go
Done

2020-10-14 15:41 UTC, SebastianMarian commented on process/block/preprocess/basePreProcess.go
> +
Done

2020-10-14 15:41 UTC, SebastianMarian commented on process/block/preprocess/basePreProcess.go
> +			continue
Added

2020-10-14 15:53 UTC, bogdan-rosianu approved these changes

2020-11-02 10:43 UTC, stefanandy approved these changes
There was no match for bad tx in logs and the txs pools have been decreasing to almost nothing

2020-11-03 17:33 UTC, merged