En 8137 delegation bughunt
ElrondNetwork/elrond-go pull request #2451
Opened 2020-11-09 06:19 UTC by BeniaminDrasovean

2020-11-09 10:37 UTC, sasurobert requested changes

2020-11-09 10:37 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	if len(args.Arguments) <= 0 {
< 2.

2020-11-09 10:37 UTC, sasurobert commented on vm/systemSmartContracts/delegation.go
> +	if len(args.Arguments) <= 0 {
< 1

2020-11-09 13:38 UTC, SebastianMarian commented on vm/systemSmartContracts/delegation.go
> +	if len(args.Arguments) <= 0 {
== 0

2020-11-09 13:51 UTC, SebastianMarian submitted a review, later dismissed

2020-11-10 07:48 UTC, BeniaminDrasovean commented on vm/systemSmartContracts/delegation.go
> +	if len(args.Arguments) <= 0 {
Right, done.

2020-11-10 07:49 UTC, BeniaminDrasovean commented on vm/systemSmartContracts/delegation.go
> +	if len(args.Arguments) <= 0 {
Done.

2020-11-10 08:34 UTC, SebastianMarian submitted a review, later dismissed

2020-11-11 07:20 UTC, sasurobert submitted a review, later dismissed

2020-11-11 14:07 UTC, sasurobert approved these changes

2020-11-11 14:20 UTC, SebastianMarian approved these changes

2020-11-11 14:21 UTC, merged