Top up rewards enhancements
ElrondNetwork/elrond-go pull request #2477
Opened 2020-11-17 10:33 UTC by AdoAdoAdo

2020-11-18 11:46 UTC, sasurobert requested changes

2020-11-18 16:26 UTC, AdoAdoAdo commented on epochStart/metachain/rewardsCreatorProxy.go
> +// RemoveBlockDataFromPools proxies the same method of the configured rewardsCreator instance
done

2020-11-18 16:27 UTC, AdoAdoAdo commented on epochStart/metachain/rewardsV2_test.go
> +	//rewardsInfo, unassigned := rwd.computeValidatorInfoPerRewardAddress(nodesRewardInfo)
done, missed that

2020-11-18 16:34 UTC, AdoAdoAdo commented on epochStart/metachain/rewardsV2_test.go
> +			case "topUpStake":
done

2020-11-24 09:50 UTC, iulianpascalau approved these changes

2020-11-24 09:56 UTC, sasurobert approved these changes

2020-11-24 09:58 UTC, merged