Feat/outport driver
ElrondNetwork/elrond-go pull request #2497
Opened 2020-11-24 07:52 UTC by miiu96

2021-07-27 07:26 UTC, sasurobert submitted a review, later dismissed

2021-07-29 08:24 UTC, iulianpascalau requested changes
minor stuff that should be done in a new PR

2021-07-29 08:24 UTC, iulianpascalau commented on node/nodeRunner.go
> +	log.Debug("starting node...")
please revert the print:
```GO
log.Debug("starting node... executeOneComponentCreationCycle")
```

2021-07-29 08:24 UTC, iulianpascalau commented on consensus/spos/bls/subroundStartRound.go
> +	sr.outportHandler = outportHandler
please do:
1. change the function signature to: `SetOutportHandler(outportHandler outport.OutportHandler) error`
2. add a check as to not let setting a nil instance
3. remove the `check.IfNil(sr.outportHandler)` check on L209

These should be done in order to slightly increase the performance and to align with the rest of the project (wherewe do not continuously check for nils)

2021-07-29 08:24 UTC, iulianpascalau commented on integrationTests/mock/nilOutport.go
> +// NewNilOutport --
remove extra `-`

2021-07-29 08:24 UTC, iulianpascalau commented on node/nodeRunner.go
> +	if check.IfNil(outportHandler) || !outportHandler.HasDrivers() {
we should not have a nil outport handler here. Should remove the `check.IfNil(outportHandler)`

2021-07-29 08:24 UTC, iulianpascalau commented on outport/disabledOutport.go
> +type disabledOutport struct{}
add tests or place this in `elrond-go/outport/disabled` pacakge

2021-07-29 08:24 UTC, iulianpascalau commented on outport/disabledOutport.go
> +func NewDisabledOutport() OutportHandler {
should return `*disabledOutport` instead of the interface in order to comply with the project

2021-07-29 08:24 UTC, iulianpascalau commented on testscommon/outportStub.go
> +// SaveValidatorsRating --
remove extra `-`

2021-08-02 13:33 UTC, iulianpascalau approved these changes

2021-08-02 13:37 UTC, sasurobert approved these changes

2021-08-02 14:29 UTC, gabi-vuls approved these changes
System test passed. 
![image](https://user-images.githubusercontent.com/46024628/127877601-f7dcca0f-e7d8-4008-9ec3-2cdb143a8440.png)

2021-08-02 14:29 UTC, merged