Fixes top up rewards
ElrondNetwork/elrond-go pull request #2504
Opened 2020-11-25 07:24 UTC by AdoAdoAdo

- fix number of blocks considered at the end of epoch for rewards v2 (previously EoE economics was computed after the rewards miniblocks on consensus validators while for block proposer it was computed before)
- use own computed economics for validation instead of the one coming from metablock header
- reject negative adjustments checks for protocol sustainability

2020-11-25 08:34 UTC, sasurobert requested changes
Can you reactivate the integration tests which were skipped in the last economics pr ?

2020-11-25 08:34 UTC, sasurobert commented on epochStart/metachain/rewardsV2.go
> +	economicsData := *computedEconomics
this is not more needed.

2020-11-25 08:52 UTC, AdoAdoAdo commented on epochStart/metachain/rewardsV2.go
> +	economicsData := *computedEconomics
done

2020-11-25 14:35 UTC, sasurobert approved these changes

2020-11-26 15:36 UTC, iulianpascalau approved these changes

2020-11-26 15:36 UTC, iulianpascalau commented on cmd/node/factory/structs.go
> +		EpochEnableV2:         systemSCConfig.StakingSystemSCConfig.StakingV2Epoch,
:+1:

2020-11-26 15:36 UTC, iulianpascalau commented on epochStart/metachain/rewardsV2_test.go
> +			case tuStake:
why these renaming?

2020-11-26 15:45 UTC, AdoAdoAdo commented on epochStart/metachain/rewardsV2_test.go
> +			case tuStake:
shadowing variables

2020-11-26 15:47 UTC, merged