EN-8500: added number of decimals in ESDT
ElrondNetwork/elrond-go pull request #2588
Opened 2020-12-14 15:23 UTC by bogdan-rosianu

Added the number of decimals when issuing a new ESDT token. It should be the 4th parameter, right after the initial supply. Also exported it in the view function

2020-12-14 17:47 UTC, sasurobert approved these changes

2020-12-14 17:47 UTC, sasurobert commented on vm/systemSmartContracts/esdt.go
> +	// format: issue@tokenName@ticker@initialSupply@numOfDecimals@optional-list-of-properties
move before the function

2020-12-15 08:18 UTC, bogdan-rosianu commented on vm/systemSmartContracts/esdt.go
> +	// format: issue@tokenName@ticker@initialSupply@numOfDecimals@optional-list-of-properties
done

2020-12-15 12:51 UTC, SebastianMarian approved these changes

2020-12-15 14:26 UTC, sasurobert requested changes

2020-12-15 14:26 UTC, sasurobert commented on process/smartContract/process.go
> +	return function == core.BuiltInFunctionESDTTransfer || function == core.BuiltInFunctionESDTBurn
delete this :D not needed

2020-12-15 14:55 UTC, bogdan-rosianu commented on integrationTests/vm/esdt/esdtProcess_test.go
> +	/* useful prints
done

2020-12-15 14:55 UTC, bogdan-rosianu commented on process/smartContract/process.go
> +	return function == core.BuiltInFunctionESDTTransfer || function == core.BuiltInFunctionESDTBurn
done

2020-12-15 14:56 UTC, SebastianMarian approved these changes

2020-12-15 14:58 UTC, SebastianMarian submitted a review, later dismissed

2020-12-15 16:44 UTC, sasurobert requested changes

2020-12-15 16:44 UTC, sasurobert commented on process/smartContract/builtInFunctions/esdtFreezeWipe.go
> +	return acntDst.DataTrieTracker().SaveKeyValue(tokenKey, nil)
we should resolve to not send back this data to the metachain -> does we can have a silent error here. with returnMessage -> cannot wipe as it was not freezed.

2020-12-15 16:44 UTC, sasurobert commented on process/smartContract/builtInFunctions/esdtFreezeWipe.go
> +	return acntDst.DataTrieTracker().SaveKeyValue(tokenKey, nil)
plus add code in ProcessIferror to not Add the created SCR if shardID := sc.shardCoordinator.ComputeId(scr.GetRcvAddr())
if shardID == core.MetachainShardId && scr.GetGasLimit() == 0 && scr.GetValue().Cmp(zero) == 0 {
   continue
}

2020-12-15 17:13 UTC, SebastianMarian submitted a review, later dismissed

2020-12-15 17:51 UTC, sasurobert commented on process/smartContract/builtInFunctions/esdtFreezeWipe.go
> +	return acntDst.DataTrieTracker().SaveKeyValue(tokenKey, nil)
my suggestion does not work - it can remain as it is. it works fine.

2020-12-15 17:51 UTC, sasurobert approved these changes

2020-12-16 08:40 UTC, sasurobert approved these changes

2020-12-16 08:43 UTC, SebastianMarian approved these changes

2020-12-16 09:41 UTC, LucianMincu approved these changes
System tests passed.

2020-12-16 09:41 UTC, merged