new arwen with fixed memory leakage
ElrondNetwork/elrond-go pull request #2735
Opened 2021-01-21 12:40 UTC by sasurobert

new arwen with fixed memory leakage

2021-01-21 17:54 UTC, iulianpascalau requested changes

2021-01-21 17:54 UTC, iulianpascalau commented on process/smartContract/testUtils.go
> +func CleanGasRefunded(scProcessorAsInterface interface{}) {
Totally disagree to use this type of code even in tests. It breaks all rules regarding clean code. Let's find some other way to do the same job. I know this file contains all sort of functions but they are terrible horrible hacks and should be removed.

2021-01-21 17:58 UTC, SebastianMarian approved these changes

2021-01-21 18:41 UTC, iulianpascalau submitted a review, later dismissed
Created task EN-8629

2021-01-21 19:58 UTC, SebastianMarian approved these changes

2021-01-21 20:02 UTC, iulianpascalau approved these changes

2021-01-22 09:09 UTC, LucianMincu approved these changes
My ram looks bigger with this one. 👍 💻

2021-01-22 09:12 UTC, merged