Refactor utils to test sc processor
ElrondNetwork/elrond-go pull request #2757
Opened 2021-01-27 19:22 UTC by stefanandy

refactored utils to testScProcessor

2021-01-27 20:23 UTC, iulianpascalau requested changes

2021-01-27 20:23 UTC, iulianpascalau commented on process/smartContract/testScProcessor.go
>  // TODO remove this file as it is a horrible hack to test some conditions
remove TODO

2021-01-27 20:23 UTC, iulianpascalau commented on process/smartContract/testScProcessor.go
> +func NewTestScProcessor(internalData *scProcessor) *TestScProcessor {
Add comment

2021-01-27 20:23 UTC, iulianpascalau commented on process/smartContract/testScProcessor.go
>  // GetLatestTestError should only be used in tests!
refactor comment

2021-01-27 20:23 UTC, iulianpascalau commented on integrationTests/vm/txsFee/utils/utils.go
> +	//require.True(t, ok)
remove comment

2021-01-28 11:47 UTC, Oxsy-SIbiu approved these changes

2021-01-28 11:50 UTC, SebastianMarian submitted a review, later dismissed

2021-01-28 12:54 UTC, iulianpascalau commented on process/smartContract/testScProcessor.go
> +// GetLatestTestError It locates the latest error in the collection of smart contracts results
Remove "It"

2021-01-28 12:56 UTC, iulianpascalau approved these changes

2021-01-28 14:42 UTC, SebastianMarian approved these changes

2021-01-28 15:13 UTC, valentincraciun99 approved these changes

2021-01-28 15:18 UTC, merged