Test coverage action[WIP]
ElrondNetwork/elrond-go pull request #2778
Opened 2021-02-08 12:23 UTC by miiu96

2021-02-08 12:47 UTC, AdoAdoAdo requested changes

2021-02-08 12:47 UTC, AdoAdoAdo commented on .github/workflows/code-coverage.yml
> +        run: bash <(curl -s https://codecov.io/bash) -f coverage.txt
newline?

2021-02-08 12:53 UTC, iulianpascalau reviewed
Only the new line

2021-02-09 12:05 UTC, miiu96 commented on .github/workflows/code-coverage.yml
> +        run: bash <(curl -s https://codecov.io/bash) -f coverage.txt
done.

2021-02-09 12:05 UTC, AdoAdoAdo approved these changes

2021-02-09 12:07 UTC, iulianpascalau submitted a review, later dismissed

2021-02-09 12:20 UTC, AdoAdoAdo approved these changes

2021-02-09 12:20 UTC, iulianpascalau approved these changes

2021-02-09 13:49 UTC, LucianMincu approved these changes

2021-02-09 13:49 UTC, merged