Unit tests new built in functions
ElrondNetwork/elrond-go pull request #2851
Opened 2021-02-25 15:31 UTC by miiu96

2021-02-25 16:22 UTC, sasurobert approved these changes

2021-03-01 09:34 UTC, sasurobert requested changes

2021-03-01 09:34 UTC, sasurobert commented on process/smartContract/builtInFunctions/esdtLocalMint.go
> +	sdtTokenKey := append(e.keyPrefix, tokenID...)
esdtTokenKey

2021-03-01 15:25 UTC, SebastianMarian commented on process/smartContract/builtInFunctions/esdtLocalMint_test.go
> +			name: "NilPouseHandler",
NilPauseHandler instead NilPouseHandler

2021-03-01 15:25 UTC, SebastianMarian commented on process/smartContract/builtInFunctions/esdtRoles_test.go
> +func TestEsdtRoles_ProcessBuiltinFunction_UnsetRolesDoesNotExitsShouldWork(t *testing.T) {
Exist instead Exits

2021-03-01 15:25 UTC, SebastianMarian commented on process/smartContract/builtInFunctions/esdtRoles_test.go
> +func TestEsdtRolest_CheckAllowedToExecuteRoleNotFind(t *testing.T) {
Roles instead Rolest

2021-03-01 15:25 UTC, SebastianMarian commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_SetSpecialRoleAlreadyExits(t *testing.T) {
Exists instead Exits

2021-03-01 15:25 UTC, SebastianMarian commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_GetAllAddressesAndRoleCallWithValueShouldErr(t *testing.T) {
AndRoles

2021-03-01 15:25 UTC, SebastianMarian commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_GetAllAddressesAndRoleCallGetExistingTokenErr(t *testing.T) {
AndRoles

2021-03-01 15:25 UTC, SebastianMarian commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_UnsetSpecialRoleCannotRemoveRoleNotExitsShouldErr(t *testing.T) {
Exists instead Exits

2021-03-02 09:51 UTC, miiu96 commented on process/smartContract/builtInFunctions/esdtLocalMint.go
> +	sdtTokenKey := append(e.keyPrefix, tokenID...)
done.

2021-03-02 09:51 UTC, miiu96 commented on process/smartContract/builtInFunctions/esdtLocalBurn_test.go
> +			name: "NilPouseHandler",
done.

2021-03-02 09:51 UTC, miiu96 commented on process/smartContract/builtInFunctions/esdtLocalMint_test.go
> +			name: "NilPouseHandler",
done.

2021-03-02 09:52 UTC, miiu96 commented on process/smartContract/builtInFunctions/esdtRoles_test.go
> +func TestEsdtRoles_ProcessBuiltinFunction_UnsetRolesDoesNotExitsShouldWork(t *testing.T) {
done.

2021-03-02 09:53 UTC, miiu96 commented on process/smartContract/builtInFunctions/esdtRoles_test.go
> +func TestEsdtRolest_CheckAllowedToExecuteRoleNotFind(t *testing.T) {
done.

2021-03-02 09:54 UTC, miiu96 commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_GetAllAddressesAndRoleCallWithValueShouldErr(t *testing.T) {
done.

2021-03-02 09:54 UTC, miiu96 commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_SetSpecialRoleAlreadyExits(t *testing.T) {
done.

2021-03-02 09:55 UTC, miiu96 commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_GetAllAddressesAndRoleCallGetExistingTokenErr(t *testing.T) {
done/

2021-03-02 09:55 UTC, miiu96 commented on vm/systemSmartContracts/esdt_test.go
> +func TestEsdt_UnsetSpecialRoleCannotRemoveRoleNotExitsShouldErr(t *testing.T) {
done.

2021-03-02 13:15 UTC, sasurobert submitted a review, later dismissed

2021-03-02 13:21 UTC, SebastianMarian approved these changes

2021-03-02 16:17 UTC, mateigraura approved these changes
System test passed

2021-03-02 18:16 UTC, sasurobert approved these changes

2021-03-02 18:16 UTC, merged