Gas schedule error when loading fails
ElrondNetwork/elrond-go pull request #2872
Opened 2021-03-02 14:37 UTC by iulianpascalau

- added new gas schedule + version
- added prints when the gas schedule fails to load
- fixed local scripts

2021-03-02 14:41 UTC, sasurobert requested changes

2021-03-02 14:41 UTC, sasurobert commented on vm/factory/systemSCFactory.go
> +var log = logger.GetOrCreate("core/forking")
Is this the correct package?

2021-03-02 14:41 UTC, sasurobert commented on vm/factory/systemSCFactory.go
Log error on line 150 as well

2021-03-02 14:43 UTC, iulianpascalau commented on vm/factory/systemSCFactory.go
> +var log = logger.GetOrCreate("core/forking")
:man_facepalming:

2021-03-02 14:45 UTC, iulianpascalau commented on vm/factory/systemSCFactory.go
> +var log = logger.GetOrCreate("core/forking")
done

2021-03-02 14:45 UTC, iulianpascalau commented on vm/factory/systemSCFactory.go
done

2021-03-02 15:22 UTC, sasurobert approved these changes

2021-03-02 15:35 UTC, raduchis approved these changes

2021-03-03 15:20 UTC, valentincraciun99 approved these changes
system testing passed

2021-03-03 15:59 UTC, merged