changed indexer interface
ElrondNetwork/elrond-go pull request #2877
Opened 2021-03-03 13:20 UTC by miiu96

- Changed indexer interface in order to prepare the ground for the refactored indexer.
- Removed unused mock from `core` package

2021-03-03 15:02 UTC, iulianpascalau requested changes

2021-03-05 12:34 UTC, miiu96 commented on cmd/storer2elastic/data/dtos.go
> +	BodyTransactions *types.Pool
done.

2021-03-05 12:38 UTC, miiu96 commented on consensus/spos/interface.go
> +	SaveRoundsInfo(roundsInfos []*types.RoundInfo)
done.

2021-03-05 13:34 UTC, iulianpascalau submitted a review, later dismissed

2021-03-10 07:11 UTC, iulianpascalau approved these changes

2021-03-10 07:15 UTC, iulianpascalau approved these changes

2021-03-19 07:17 UTC, iulianpascalau approved these changes

2021-03-19 07:47 UTC, closed without merging