Execution component for scheduled transactions
ElrondNetwork/elrond-go pull request #2917
Opened 2021-03-19 16:27 UTC by SebastianMarian

* Implemented execution component for scheduled transactions

2021-03-22 12:02 UTC, sasurobert requested changes

2021-03-22 18:43 UTC, SebastianMarian commented on process/block/preprocess/transactionsV2.go
> +		isTxTargetedForDeletion := errors.Is(err, process.ErrLowerNonceInTransaction) || errors.Is(err, process.ErrInsufficientFee)
Done

2021-03-23 11:06 UTC, sasurobert submitted a review, later dismissed

2021-03-25 13:01 UTC, AdoAdoAdo submitted a review, later dismissed

2021-03-29 14:59 UTC, sasurobert approved these changes

2021-03-30 14:00 UTC, merged