integration test for validator to delegation
ElrondNetwork/elrond-go pull request #3061
Opened 2021-04-29 16:43 UTC by bogdan-rosianu

WIP

2021-05-05 15:12 UTC, iulianpascalau requested changes
Managed to reduce the duplicated code inside the integration tests. Will open a PR against this one

2021-05-05 15:12 UTC, iulianpascalau commented on integrationTests/frontend/staking/staking_test.go
> +const delegationManagementKey = "delegationManagement"
these should be placed in the first part of the file

2021-05-05 15:46 UTC, iulianpascalau commented on integrationTests/frontend/staking/staking_test.go
> +	//txData = "makeNewContractFromValidatorData" + "@" + hex.EncodeToString() + "@" + pubKey + "@" + frontendHexSignature
done

2021-05-05 15:46 UTC, iulianpascalau commented on integrationTests/frontend/staking/staking_test.go
> +	//txData = "makeNewContractFromValidatorData" + "@" + hex.EncodeToString() + "@" + pubKey + "@" + frontendHexSignature
done

2021-05-05 15:46 UTC, iulianpascalau commented on integrationTests/frontend/staking/staking_test.go
> +const delegationManagementKey = "delegationManagement"
done

2021-05-06 08:28 UTC, iulianpascalau approved these changes
good cleanup :+1:

2021-05-06 08:29 UTC, bogdan-rosianu commented on integrationTests/frontend/staking/staking_test.go
> +func TestValidatorToDelegationManagerWithNewContract(t *testing.T) {
done

2021-05-06 08:34 UTC, sasurobert approved these changes

2021-05-06 12:55 UTC, merged