added command "make lint"
ElrondNetwork/elrond-go pull request #3064
Opened 2021-05-04 09:20 UTC by miiu96

Added in the Makefile command "make lint" that will run` golangci linter.`
This command will check if the `golangci linter` is installed ( in case of not installed, will install the latest tag of the `golangci linter`) and after that will run the linter.

2021-05-04 09:39 UTC, iulianpascalau submitted a review, later dismissed

2021-05-04 11:34 UTC, bogdan-rosianu requested changes
works only for the first issue right now

2021-05-06 06:58 UTC, bogdan-rosianu approved these changes

2021-05-06 07:27 UTC, iulianpascalau requested changes

2021-05-06 07:27 UTC, iulianpascalau commented on crypto/signing/multisig/pubkeys.go
> +	pk := make([]crypto.PublicKey, len(pubKeys))
please use:
```GO
pk := make([]crypto.PublicKey, 0, len(pubKeys))
for _, pubKeyStr := range pubKeys {
		if pubKeyStr == "" {
			return nil, crypto.ErrEmptyPubKeyString
		}
	        //................
		pk = append(pk, pubKey)
}
```

2021-05-06 07:33 UTC, miiu96 commented on crypto/signing/multisig/pubkeys.go
> +	pk := make([]crypto.PublicKey, len(pubKeys))
done.

2021-05-06 08:28 UTC, iulianpascalau approved these changes

2021-05-07 06:33 UTC, bogdan-rosianu approved these changes

2021-05-07 09:23 UTC, gabi-vuls approved these changes
System test passed.

2021-05-07 12:21 UTC, merged