En 9704 peer hb resolvers
ElrondNetwork/elrond-go pull request #3087
Opened 2021-05-12 09:11 UTC by iulianpascalau

- added peer heartbeat resolver
- removed part of the duplicated code found in resolvers

2021-05-12 11:16 UTC, AdoAdoAdo requested changes

2021-05-12 11:16 UTC, AdoAdoAdo commented on dataRetriever/resolvers/peerHeartbeatResolver.go
> +func (res *peerheartbeatResolver) fetchPhbAsByteSlice(pk []byte) ([]byte, error) {
fetchPeerHeartbeat...?

2021-05-12 12:42 UTC, sasurobert submitted a review, later dismissed

2021-05-13 05:33 UTC, AdoAdoAdo approved these changes

2021-05-13 06:08 UTC, sasurobert approved these changes

2021-05-13 06:08 UTC, merged