Safe closer implementation
ElrondNetwork/elrond-go pull request #3190
Opened 2021-06-18 08:49 UTC by iulianpascalau

- implemented a safe closer to be used in the components that need fast closing means on the exposed methods

2021-06-18 09:17 UTC, BeniaminDrasovean approved these changes

2021-06-18 11:29 UTC, bogdan-rosianu requested changes

2021-06-18 11:29 UTC, bogdan-rosianu commented on core/closing/safeChanCloser.go
> +	mut     sync.Mutex
please rename to `closeMut`

2021-06-18 11:31 UTC, iulianpascalau commented on core/closing/safeChanCloser.go
> +	mut     sync.Mutex
done

2021-06-18 11:31 UTC, bogdan-rosianu approved these changes

2021-06-18 11:32 UTC, BeniaminDrasovean approved these changes

2021-06-21 20:25 UTC, LucianMincu approved these changes
System tests passed.

2021-06-21 20:25 UTC, merged