Moved FullArchive config flag
ElrondNetwork/elrond-go pull request #3223
Opened 2021-06-28 12:50 UTC by iulianpascalau

- moved full archive config in prefs.toml

2021-06-28 13:07 UTC, raduchis submitted a review, later dismissed

2021-06-28 13:31 UTC, miiu96 approved these changes

2021-06-28 14:26 UTC, bogdan-rosianu requested changes

2021-06-28 14:28 UTC, iulianpascalau commented on cmd/node/config/prefs.toml
> +   # FullArchive, if enabled, will make the node able to respond to requests from past, old epochs.
No, it is able to respond as we have the new implementation of pruning storers. Keeping or not the database is done by another flag. I do not think we need to change this.

2021-06-28 14:33 UTC, bogdan-rosianu approved these changes

2021-06-29 07:12 UTC, bogdan-rosianu approved these changes

2021-06-29 07:12 UTC, bogdan-rosianu commented on dataRetriever/resolvers/epochproviders/arithmeticEpochProvider.go
> +	isTimestampInvalid := newTimestamp == 0
can this happen on a "happy" scenario?

2021-06-29 09:16 UTC, miiu96 approved these changes

2021-06-29 09:16 UTC, raduchis submitted a review, later dismissed

2021-07-01 09:00 UTC, bogdan-rosianu approved these changes

2021-07-01 09:00 UTC, miiu96 approved these changes

2021-07-01 09:02 UTC, sasurobert approved these changes

2021-07-01 10:09 UTC, LucianMincu approved these changes
Initial system tests passed. 
More testing will follow on the development branch.

2021-07-01 10:09 UTC, merged