Merge ecc in development
ElrondNetwork/elrond-go pull request #3289
Opened 2021-07-22 12:54 UTC by andrei-diaconescu

2021-07-22 13:37 UTC, bogdan-rosianu submitted a review, later dismissed

2021-07-22 13:37 UTC, bogdan-rosianu commented on integrationTests/vm/arwen/testdata/c-api-tests/cbuiltins.c
> +}
empty line at the end of the file?

2021-07-22 13:37 UTC, bogdan-rosianu commented on integrationTests/vm/arwen/testdata/c-api-tests/crypto/elrond.json
> +}
empty line at the end of the file?

2021-07-22 13:37 UTC, bogdan-rosianu commented on integrationTests/vm/arwen/testdata/c-api-tests/ecBenchmark/ecBenchmark.export
> +p521ScalarMultEcTest
empty line at the end of the file?

2021-07-22 13:37 UTC, bogdan-rosianu commented on integrationTests/vm/arwen/testdata/c-api-tests/ecBenchmark/elrond.json
> +}
empty line at the end of the file?

2021-07-23 10:06 UTC, AdoAdoAdo requested changes

2021-07-23 10:06 UTC, AdoAdoAdo commented on integrationTests/vm/arwen/testdata/c-api-tests/ecBenchmark/ecBenchmark.c
> +const int p224SMResultLength = 28;
please remove these ...Length constants if not used

2021-07-23 10:13 UTC, AdoAdoAdo commented on integrationTests/vm/arwen/testdata/c-api-tests/ecBenchmark/ecBenchmark.c
> +const int lengthOfScalar = 60;
I see you use this for different curves, so I suspect you need different scalar lengths
why not give a parameter to repeatDoubleAndScalarMult for the scalar lenght, and pass that depending on the curve.

2021-07-23 13:51 UTC, AdoAdoAdo submitted a review, later dismissed

2021-07-23 13:58 UTC, sasurobert submitted a review, later dismissed

2021-07-23 16:31 UTC, bogdan-rosianu submitted a review, later dismissed

2021-07-30 08:58 UTC, sasurobert approved these changes

2021-07-30 09:03 UTC, iulianpascalau approved these changes

2021-07-30 09:03 UTC, bogdan-rosianu approved these changes

2021-07-30 09:23 UTC, sasurobert approved these changes

2021-07-30 09:23 UTC, merged