Csv file mode change
ElrondNetwork/elrond-go pull request #3290
Opened 2021-07-23 07:43 UTC by iulianpascalau

- changed the output csv file mode perm

2021-07-23 07:45 UTC, bogdan-rosianu approved these changes

2021-07-23 07:49 UTC, bogdan-rosianu requested changes
please check all occurrences of `os.ModePerm`

2021-07-23 07:58 UTC, SebastianMarian approved these changes

2021-07-23 08:06 UTC, SebastianMarian commented on cmd/assessment/main.go
> +	return ioutil.WriteFile(outputFileName, buff.Bytes(), core.FileModeUserReadWrite)
please check all occurrences of os.ModePerm

2021-07-23 09:10 UTC, raduchis submitted a review, later dismissed

2021-07-23 09:17 UTC, raduchis submitted a review, later dismissed

2021-07-23 10:40 UTC, bogdan-rosianu approved these changes

2021-07-23 12:04 UTC, SebastianMarian approved these changes

2021-07-23 13:01 UTC, bogdan-rosianu approved these changes

2021-07-23 13:03 UTC, raduchis approved these changes

2021-07-23 13:05 UTC, SebastianMarian approved these changes

2021-07-26 08:05 UTC, gabi-vuls approved these changes
![image](https://user-images.githubusercontent.com/46024628/126954949-622d07d7-658d-4cb4-9591-407b698c6580.png)
System test passed.

2021-07-26 11:54 UTC, merged