ESDT transfer role, no global burn/mint
ElrondNetwork/elrond-go pull request #3318
Opened 2021-07-29 12:55 UTC by sasurobert

No more global mint burn
ESDT transfer role

2021-07-30 11:41 UTC, iulianpascalau reviewed
please add in elrond-go/genesis/process/shardGenesisCreator.go L61:
```GO
BuiltInFunctionOnMetaEnableEpoch: unreachableEpoch,
```

2021-08-02 09:30 UTC, raduchis requested changes
small changes and clarifications needed

2021-08-02 09:31 UTC, sasurobert commented on genesis/process/shardGenesisBlockCreator.go
> +		GlobalBurnMintDisableEpoch:   unreachableEpoch,
this is genesis block processor.

2021-08-02 09:33 UTC, sasurobert commented on factory/apiResolverFactory.go
> +		GlobalBurnMintDisableEpoch:   esdtGlobalMintBurnDisableEpoch,
done

2021-08-02 09:33 UTC, sasurobert commented on process/smartContract/builtInFunctions/factory.go
> +		GlobalBurnMintDisableEpoch:          args.GlobalBurnMintDisableEpoch,
done

2021-08-02 09:58 UTC, sasurobert commented on process/transaction/metaProcess.go
> +		builtInFunctionEnableEpoch: args.BuiltInFunctionOnMetachainEnableEpoch,
done

2021-08-02 09:59 UTC, sasurobert commented on process/smartContract/process.go
> +		vmOutputCacher:                        args.VMOutputCacher,
done

2021-08-02 10:00 UTC, sasurobert commented on vm/systemSmartContracts/esdt.go
> +		endOfEpochSCAddress:        args.EndOfEpochSCAddress,
done

2021-08-02 10:00 UTC, sasurobert commented on vm/systemSmartContracts/esdt.go
> +		e.eei.AddReturnMessage("global burn is not more enabled, use local burn")
done

2021-08-02 10:00 UTC, sasurobert commented on vm/systemSmartContracts/esdt.go
> +		e.eei.AddReturnMessage("global mint is not more enabled, use local mint")
done

2021-08-02 10:01 UTC, sasurobert commented on config/epochConfig.go
> +	GlobalMintBurnDisableEpoch                  uint32
done

2021-08-02 10:03 UTC, sasurobert commented on vm/systemSmartContracts/esdt.go
> +	if e.flagGlobalMintBurn.IsSet() && initialSupply.Cmp(zero) <= 0 {
done

2021-08-02 10:37 UTC, iulianpascalau approved these changes

2021-08-02 10:38 UTC, raduchis commented on factory/apiResolverFactory.go
> +		GlobalBurnMintDisableEpoch:   esdtGlobalMintBurnDisableEpoch,
ok

2021-08-02 10:39 UTC, raduchis commented on genesis/process/shardGenesisBlockCreator.go
> +		GlobalBurnMintDisableEpoch:   unreachableEpoch,
ok

2021-08-02 10:39 UTC, raduchis commented on process/smartContract/builtInFunctions/factory.go
> +		GlobalBurnMintDisableEpoch:          args.GlobalBurnMintDisableEpoch,
ok

2021-08-02 10:39 UTC, raduchis commented on vm/systemSmartContracts/esdt.go
> +	transferRoleEnabpeEpoch    uint32
ok

2021-08-02 10:42 UTC, raduchis submitted a review, later dismissed

2021-08-02 14:38 UTC, raduchis approved these changes

2021-08-02 14:38 UTC, iulianpascalau submitted a review, later dismissed

2021-08-03 08:48 UTC, gabi-vuls approved these changes
![image](https://user-images.githubusercontent.com/46024628/127986602-65dbb4ca-dcef-4b75-9975-2a462b11e3fb.png)
System test passed.

2021-08-09 10:46 UTC, iulianpascalau approved these changes

2021-08-09 10:46 UTC, iulianpascalau commented on integrationTests/testProcessorNode.go
> +	enableEpochs config.EnableEpochs,
:+1: :1st_place_medal:

2021-08-09 11:43 UTC, iulianpascalau approved these changes

2021-08-09 11:44 UTC, raduchis submitted a review, later dismissed

2021-08-09 12:04 UTC, iulianpascalau approved these changes

2021-08-09 12:04 UTC, raduchis approved these changes

2021-08-09 12:19 UTC, iulianpascalau approved these changes

2021-08-09 13:19 UTC, raduchis approved these changes

2021-08-09 15:02 UTC, LucianMincu approved these changes
System tests passed.

2021-08-09 15:34 UTC, merged