latest arwen and vm common
ElrondNetwork/elrond-go pull request #3319
Opened 2021-07-29 15:05 UTC by miiu96

- Latest arwens  commits and vm common

2021-07-29 15:12 UTC, iulianpascalau submitted a review, later dismissed

2021-07-30 06:08 UTC, iulianpascalau submitted a review, later dismissed

2021-07-30 09:45 UTC, iulianpascalau requested changes

2021-07-30 09:45 UTC, iulianpascalau commented on go.mod
> +	github.com/ElrondNetwork/arwen-wasm-vm/v1_4 v1.4.3
this is not latest, that is why it works without defining managed buffers. But this won't reference the last changes in vmcommon.

2021-07-30 10:25 UTC, iulianpascalau approved these changes

2021-07-30 10:26 UTC, iulianpascalau requested changes

2021-07-30 10:26 UTC, iulianpascalau commented on go.mod
> +replace github.com/ElrondNetwork/arwen-wasm-vm/v1_2 v1.2.28 => github.com/ElrondNetwork/arwen-wasm-vm v1.2.29-0.20210729145932-3dbaf2426369
I think it will work only if you remove the commit hashes. Let's use just the release tags.

2021-07-30 12:21 UTC, iulianpascalau approved these changes

2021-07-30 16:01 UTC, gabi-vuls approved these changes
System test passed. 
![image](https://user-images.githubusercontent.com/46024628/127680210-0f6869fe-f1ba-4626-84db-d7533630a0d5.png)

2021-07-30 16:12 UTC, bogdan-rosianu approved these changes

2021-07-30 17:35 UTC, merged