Prints for the pid <-> BLS PK mapping
ElrondNetwork/elrond-go pull request #3764
Opened 2022-02-08 08:43 UTC by iulianpascalau

- added prints for the pid <-> BLS PK mapping

2022-02-08 08:48 UTC, bogdan-rosianu requested changes

2022-02-08 08:48 UTC, bogdan-rosianu commented on sharding/networksharding/peerShardMapper.go
> +// updatePeerIDPublicKey will update the pis <-> pk mapping, returning true if the pair is a new known pair
pid*

2022-02-08 08:49 UTC, iulianpascalau commented on sharding/networksharding/peerShardMapper.go
> +// updatePeerIDPublicKey will update the pis <-> pk mapping, returning true if the pair is a new known pair
fixed

2022-02-08 08:52 UTC, bogdan-rosianu approved these changes

2022-02-08 08:53 UTC, sstanculeanu approved these changes

2022-02-08 08:53 UTC, raduchis approved these changes

2022-02-08 08:53 UTC, raduchis commented on sharding/networksharding/peerShardMapper.go
> +// removePidAssociation remove the pid association between the pid and public key, returning old public key stored, if existing
removePidAssociation remove**s** ....

2022-02-08 08:56 UTC, bogdan-rosianu approved these changes

2022-02-08 08:56 UTC, raduchis approved these changes

2022-02-08 08:56 UTC, sstanculeanu approved these changes

2022-02-09 11:25 UTC, gabi-vuls approved these changes
System test passed.

2022-02-10 10:16 UTC, merged