unit tests process metablock:
ElrondNetwork/elrond-go pull request #3787
Opened 2022-02-11 18:31 UTC by ssd04

- updateEpochStartHeader
- createEpochStartBody

2022-02-14 13:49 UTC, AdoAdoAdo commented on process/block/metablock_test.go
> +	assert.Equal(t, accFeesInEpoch, header.GetAccumulatedFeesInEpoch())
can you also check end of epoch economics? 
you can set the ComputeEndOfEpochEconomicsCalled to return some predefined value, and have that checked on the header.GetEpochStartHandler().GetEconomicsHandler()

2022-02-14 14:15 UTC, AdoAdoAdo submitted a review, later dismissed

2022-02-15 13:01 UTC, mariusmihaic requested changes

2022-02-15 13:20 UTC, ssd04 commented on process/block/metablock_test.go
> +		err := mp.ProcessEpochStartMetaBlock(header, body)
right :+1:

2022-02-15 13:21 UTC, ssd04 commented on process/block/metablock_test.go
> +	hash := []byte("hash1")
:+1:

2022-02-15 13:25 UTC, ssd04 commented on process/block/metablock_test.go
> +func TestMetaProcessor_UpdateEpochStartHeader(t *testing.T) {
I usually preferred to to have a least different tests for working and failing paths, but here there is too much duplicate code. will compress them :+1:

2022-02-15 13:37 UTC, ssd04 commented on process/block/metablock_test.go
> +		header := &block.MetaBlock{
right :+1: this was due to copying from the happy path test below, forgot to cleanup

2022-02-15 13:37 UTC, ssd04 commented on process/block/metablock_test.go
> +		header := &block.MetaBlock{
right :+1: this was due to copying from the happy path test below, forgot to cleanup

2022-02-15 13:42 UTC, ssd04 commented on process/block/metablock_test.go
> +		header := &block.MetaBlock{
since the inner tests will also run in parallel, it may lead to unexpected results if we use the same variable

2022-02-15 13:52 UTC, ssd04 commented on process/block/metablock_test.go
> +			ProcessSystemSmartContractCalled: func(validatorInfos map[uint32][]*state.ValidatorInfo, nonce uint64, epoch uint32) error {
:+1:

2022-02-15 14:09 UTC, ssd04 commented on process/block/metablock_test.go
> +				wasCalled = true
done

2022-02-15 14:09 UTC, ssd04 commented on process/block/metablock_test.go
> +			CreateRewardsMiniBlocksCalled: func(
done

2022-02-21 13:16 UTC, mariusmihaic commented on process/block/metablock_test.go
>  func TestMetaProcessor_UpdateEpochStartHeaderShouldFail(t *testing.T) {
Please delete this

2022-02-21 13:16 UTC, mariusmihaic commented on process/block/metablock_test.go
> +		header := &block.MetaBlock{
Right, in this func, the content of the header is altered

2022-02-21 14:47 UTC, ssd04 commented on process/block/metablock_test.go
>  func TestMetaProcessor_UpdateEpochStartHeaderShouldFail(t *testing.T) {
:+1: thanks

2022-02-22 10:39 UTC, AdoAdoAdo approved these changes

2022-02-22 11:08 UTC, mariusmihaic approved these changes

2022-02-22 13:47 UTC, closed without merging