Fix fetch miniblock from storer only
ElrondNetwork/elrond-go pull request #3843
Opened 2022-02-24 15:52 UTC by ssd04

Fetch miniblock by specifying also the epoch.

2022-02-24 16:16 UTC, AdoAdoAdo approved these changes

2022-03-01 09:22 UTC, bogdan-rosianu approved these changes

2022-03-01 11:59 UTC, AdoAdoAdo requested changes

2022-03-01 11:59 UTC, AdoAdoAdo commented on api/groups/internalGroup.go
> +	roundStr := c.Param("epoch")
epochStr?

2022-03-01 12:04 UTC, ssd04 commented on api/groups/internalGroup.go
> +	roundStr := c.Param("epoch")
done. thanks

2022-03-01 12:07 UTC, AdoAdoAdo approved these changes

2022-03-01 12:10 UTC, bogdan-rosianu approved these changes

2022-03-01 12:14 UTC, merged