Hotfix disabled persister on trie sync
ElrondNetwork/elrond-go pull request #3949
Opened 2022-03-29 18:30 UTC by iulianpascalau

2022-03-29 20:24 UTC, SebastianMarian approved these changes

2022-03-30 08:02 UTC, bogdan-rosianu approved these changes

2022-03-30 10:59 UTC, bogdan-rosianu requested changes

2022-03-30 10:59 UTC, bogdan-rosianu commented on process/block/preprocess/transactionsV2.go
> +			"data", tx.Data,
please revert the changes for the data field. it is directly convertible to string and the logger will display them as hex, which implies a further step when debugging

2022-03-30 10:59 UTC, bogdan-rosianu commented on process/block/preprocess/transactionsV2.go
> +			"data", tx.Data,
applicable for the entire changeset of this commit

2022-03-30 10:59 UTC, bogdan-rosianu commented on epochStart/bootstrap/startInEpochScheduled.go
> +				"intermediate tx data", txHandler.GetData(),
revert for the data field

2022-03-30 11:05 UTC, SebastianMarian approved these changes

2022-03-30 11:45 UTC, bogdan-rosianu submitted a review, later dismissed

2022-03-30 11:52 UTC, SebastianMarian submitted a review, later dismissed

2022-03-30 12:18 UTC, bogdan-rosianu approved these changes

2022-03-30 18:14 UTC, SebastianMarian approved these changes

2022-03-30 19:20 UTC, gabi-vuls approved these changes
System test passed.

2022-03-30 20:33 UTC, merged