fix-transferRole-check-on-esdtTransfer
ElrondNetwork/elrond-go pull request #4014
Opened 2022-04-22 06:26 UTC by sasurobert

integrated new flag

2022-04-22 06:35 UTC, andrei-marinica submitted a review, later dismissed

2022-04-22 06:46 UTC, dragos-rebegea approved these changes

2022-04-22 06:49 UTC, iulianpascalau commented on genesis/process/shardGenesisBlockCreator.go
> +		OptimizeNFTStoreEnableEpoch:    enableEpochs.OptimizeNFTStoreEnableEpoch,
this was a forgotten flag. Does the code is still backwards compatible now?

2022-04-22 06:49 UTC, iulianpascalau commented on go.mod
> +	github.com/ElrondNetwork/elrond-vm-common v1.2.14-0.20220421185714-edf68ab67a9e
proper release

2022-04-22 16:08 UTC, popenta approved these changes
@@                            Log scanner                                  @@
##                            fix-transferRole-check-on-transfer           ##
================================================================================
- Known Warnings              450
- New Warnings                342
- Known Errors                0
- New Errors                  0
- Panics                      0
================================================================================

2022-04-23 09:39 UTC, iulianpascalau requested changes
Looks good :+1: 
We will wait until the `feat/release-2022-April` gets merged and then re-target this in `rc/2022-may` 
Requested changes only to prevent accidental merges

2022-04-23 11:49 UTC, iulianpascalau commented on genesis/process/shardGenesisBlockCreator.go
> +		OptimizeNFTStoreEnableEpoch:    enableEpochs.OptimizeNFTStoreEnableEpoch,
having a second thought, let's keep it this way as this is the correct way. Will deal with the import-db process afterwards

2022-04-23 11:49 UTC, iulianpascalau approved these changes

2022-04-23 12:37 UTC, andrei-marinica approved these changes

2022-04-25 11:16 UTC, LucianMincu approved these changes
System tests passed.

2022-04-25 11:16 UTC, merged