Vmcommon storage updates
ElrondNetwork/elrond-go pull request #4150
Opened 2022-06-02 12:24 UTC by sasurobert

Vmcommon storage updates

2022-06-02 12:29 UTC, iulianpascalau commented on cmd/node/config/config.toml
> +    AutomaticCrawlerAddress = "erd1fpkcgel4gcmh8zqqdt043yfcn5tyx8373kg6q2qmkxzu4dqamc0swts65c"
please move this in systemSmartContractsConfig.toml

2022-06-02 13:12 UTC, raduchis submitted a review, later dismissed

2022-06-02 13:29 UTC, bogdan-rosianu requested changes
please update the esdt storer stub, as the tests are failing:
```
node/options_test.go#L285

cannot use esdtStorer (variable of type *"github.com/ElrondNetwork/elrond-go/node/mock".EsdtStorageHandlerStub) as type vmcommon.ESDTNFTStorageHandler in argument to WithESDTNFTStorageHandler
```

2022-06-02 18:08 UTC, iulianpascalau requested changes
.

2022-06-02 18:11 UTC, iulianpascalau approved these changes

2022-06-02 18:52 UTC, gabi-vuls submitted a review, later dismissed
System test passed.

2022-06-03 13:59 UTC, bogdan-rosianu requested changes

2022-06-03 13:59 UTC, bogdan-rosianu commented on node/mock/esdtStorageHandlerStub.go
> +	"math/big"
imports are not sorted

2022-06-08 07:41 UTC, sasurobert commented on node/mock/esdtStorageHandlerStub.go
> +	"math/big"
done

2022-06-08 07:42 UTC, bogdan-rosianu approved these changes

2022-06-08 07:44 UTC, gabi-vuls approved these changes
System test passed.

2022-06-08 08:13 UTC, iulianpascalau approved these changes

2022-06-08 09:44 UTC, merged