added backwardsCompatibility for partialExecution on epochStartData
ElrondNetwork/elrond-go pull request #4331
Opened 2022-07-30 12:04 UTC by raduchis

## Description of the reasoning behind the pull request (what feature was missing / how the problem was manifesting itself / what was the motive behind the refactoring)
- backwards compatibility for the partialExecution on the meta epochStartData

  
## Proposed Changes
- added MiniBlockPartialExecutionEnableEpoch to epochStartData to take partialExecution enableEpooch into consideration

## Testing procedure
- import-db should work now

2022-07-30 12:07 UTC, sasurobert approved these changes

2022-08-01 09:11 UTC, SebastianMarian submitted a review, later dismissed

2022-08-01 09:19 UTC, SebastianMarian commented on process/block/baseProcess.go
> +	// TODO: check if partialExecutionEnableEpoch is not needed
Actually in L646 there is:
```
	if !bp.flagScheduledMiniBlocks.IsSet() {
		return nil
	}
```
And this line protects for backwards compatibility for nil vs empty/something in the reserved field starting with the scheduled txs activation epoch. As partial mb execution appeared later, when already the reserved field could not be nil anymore, the case should be solved.

2022-08-01 12:04 UTC, popenta approved these changes
@@                            Log scanner                                  @@
##                            fix-partial-execution-epochstartdata         ##
================================================================================
- Known Warnings              19
- New Warnings                0
- Known Errors                1
- New Errors                  2
- Panics                      1
================================================================================

2022-08-01 14:20 UTC, iulianpascalau requested changes

2022-08-01 14:20 UTC, iulianpascalau commented on process/block/baseProcess.go
> +	// TODO: check if partialExecutionEnableEpoch is not needed
TODO still relevant?

2022-08-01 14:25 UTC, iulianpascalau approved these changes

2022-08-01 14:25 UTC, raduchis commented on process/block/baseProcess.go
> +	// TODO: check if partialExecutionEnableEpoch is not needed
nope, removed

2022-08-01 14:32 UTC, popenta approved these changes
system test passed

2022-08-01 14:51 UTC, sasurobert approved these changes

2022-08-01 16:02 UTC, SebastianMarian approved these changes

2022-08-01 16:12 UTC, merged