refactor interceptor resolver: use mutex in event struct
ElrondNetwork/elrond-go pull request #4518
Opened 2022-09-27 05:53 UTC by ssd04

## Description of the reasoning behind the pull request (what feature was missing / how the problem was manifesting itself / what was the motive behind the refactoring)
- 
- 
- 
  
## Proposed Changes
- 
- 
- 

## Testing procedure
- 
- 
-

2022-09-28 12:33 UTC, AdoAdoAdo requested changes

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
can be RLock

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
can be RLock

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
can be RLock

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +		ev.mutEvent.Unlock()
:+1:

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +		ev.mutEvent.Lock()
RLock

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +	req.mutEvent.Unlock()
:+1:

2022-09-28 12:33 UTC, AdoAdoAdo commented on debug/resolver/interceptorResolver.go
> +		ev.mutEvent.Lock()
RLock

2022-09-28 12:39 UTC, ssd04 commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
thanks, done

2022-09-28 12:39 UTC, ssd04 commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
done

2022-09-28 12:40 UTC, ssd04 commented on debug/resolver/interceptorResolver.go
> +	ev.mutEvent.Lock()
done

2022-09-28 13:03 UTC, AdoAdoAdo approved these changes

2022-09-28 13:10 UTC, iulianpascalau approved these changes

2022-09-29 07:40 UTC, gabi-vuls approved these changes
System test passed.

2022-10-04 15:22 UTC, merged