Integrate new logger
ElrondNetwork/elrond-go pull request #4530
Opened 2022-09-29 07:50 UTC by miiu96

## Description of the reasoning behind the pull request (what feature was missing / how the problem was manifesting itself / what was the motive behind the refactoring)
- Removed the logic that saves generated logs in files.
- PR from elrond-go-logger: https://github.com/ElrondNetwork/elrond-go-logger/pull/13
  
## Proposed Changes
-  Moved all the logic that saves logs in files in the `elrond-go-logger` repository 

## Testing procedure
- Run a system test with `*:TRACE` and check if logs files are generated.

2022-09-29 07:51 UTC, iulianpascalau commented on go.mod
> +	github.com/ElrondNetwork/elrond-go-logger v1.0.8-0.20220901113442-d5ad00505a23
proper release

2022-10-04 16:51 UTC, iulianpascalau approved these changes

2022-10-05 17:11 UTC, iulianpascalau requested changes

2022-10-05 17:11 UTC, iulianpascalau commented on go.mod
> +	github.com/ElrondNetwork/elrond-go-logger v1.0.8
please use the latest v1.0.9 tag

2022-10-06 09:00 UTC, miiu96 commented on go.mod
> +	github.com/ElrondNetwork/elrond-go-logger v1.0.8
done

2022-10-06 13:04 UTC, iulianpascalau approved these changes

2022-10-18 06:37 UTC, merged