fix custom meta DB remover
ElrondNetwork/elrond-go pull request #4642
Opened 2022-10-25 14:56 UTC by bogdan-rosianu

## Reasoning behind the pull request
- due to the old implementation (CreateForShard, CreateForMeta), the fix done in #4505 was not enabled for metachain as well 
  
## Proposed changes
- use the factory for custom db remover

## Testing procedure
- same as #4505 , but for meta nodes only

## Pre-requisites

Based on the [Contributing Guidelines](CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2022-10-25 15:16 UTC, andreibancioiu submitted a review, later dismissed

2022-10-25 15:55 UTC, SebastianMarian approved these changes

2022-10-25 15:55 UTC, SebastianMarian commented on storage/factory/pruningStorerFactory.go
> +// TODO: split in 2 components shardStorageServiceCreator and metStorageServiceCreator that have a base which will contain the
typo: metStorageServiceCreator

2022-10-25 16:05 UTC, iulianpascalau requested changes

2022-10-25 16:05 UTC, iulianpascalau commented on storage/factory/pruningStorerFactory.go
> +// TODO: split in 2 components shardStorageServiceCreator and metStorageServiceCreator that have a base which will contain the
I've expected the proper refactor work

2022-10-27 07:53 UTC, iulianpascalau approved these changes
Green just to unlock this PR since I've pushed in the branch

2022-10-27 08:13 UTC, SebastianMarian approved these changes

2022-10-28 12:21 UTC, gabi-vuls approved these changes
System test passed.

2022-10-31 07:40 UTC, andreibancioiu approved these changes

2022-10-31 11:05 UTC, merged