Move AppStatusHandler to StatusCoreComponents
ElrondNetwork/elrond-go pull request #4655
Opened 2022-10-28 11:16 UTC by sstanculeanu

## Reasoning behind the pull request
- now with the newly added StatusCoreComponents, AppStatusHandler belongs there
  
## Proposed changes
- moved the components, no logic changed

## Testing procedure
- standard system test

## Pre-requisites

Based on the [Contributing Guidelines](CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2022-10-28 14:11 UTC, bogdan-rosianu requested changes

2022-10-28 14:15 UTC, sstanculeanu commented on factory/interface.go
> +// PersistenStatusHandler defines a persistend status handler
fixed

2022-10-28 14:16 UTC, sstanculeanu commented on factory/statusCore/statusCoreComponents.go
> +			log.Warn("cannot init AppStatusFacade", "error", err)
correct, updated

2022-10-28 14:24 UTC, sstanculeanu commented on factory/statusCore/statusCoreComponents.go
> +	err = metrics.InitConfigMetrics(handler, sccf.epochConfig, sccf.economicsConfig, sccf.coreComp.GenesisNodesSetup())
done

2022-10-28 14:28 UTC, bogdan-rosianu submitted a review, later dismissed

2022-10-31 09:06 UTC, iulianpascalau reviewed
Good cleanup :+1:

2022-10-31 09:06 UTC, iulianpascalau commented on integrationTests/testConsensusNode.go
> +	factory2 "github.com/ElrondNetwork/elrond-go/testscommon/factory"
rename to testFactory?

2022-10-31 09:10 UTC, bogdan-rosianu approved these changes

2022-10-31 10:22 UTC, iulianpascalau submitted a review, later dismissed

2022-11-01 15:13 UTC, gabi-vuls approved these changes
System test passed.

2022-11-01 19:58 UTC, bogdan-rosianu approved these changes

2022-11-01 21:14 UTC, gabi-vuls approved these changes

2022-11-01 21:52 UTC, iulianpascalau approved these changes

2022-11-02 04:09 UTC, merged