remove collections index rc
ElrondNetwork/elrond-go pull request #4726
Opened 2022-11-22 13:02 UTC by miiu96

## Reasoning behind the pull request
- Upgrade elastic-indexer-go module.
- Removed from external.toml file the collections index.
  
## Proposed changes
- Upgrade the `elastic-indexer-go` module with a version that will no longer index data in the `collections` index. 
- PR from elastic-indexer-go module: https://github.com/ElrondNetwork/elastic-indexer-go/pull/189

## Testing procedure
- Run a system test and check in the Elasticsearch databases that the collections index will no longer exist.

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/ElrondNetwork/elrond-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

2022-11-22 13:04 UTC, iulianpascalau requested changes

2022-11-22 13:04 UTC, iulianpascalau commented on go.sum
> +github.com/ElrondNetwork/elastic-indexer-go v1.3.2-0.20221122125610-ed6f40a9dd94 h1:wAOwGLPzspYBNzmHGdR9lsRPT00MhHpWiD0wYPLVA8k=
proper version

2022-11-24 09:46 UTC, gabi-vuls submitted a review, later dismissed
system test passed

2022-11-24 12:36 UTC, gabi-vuls approved these changes

2022-11-24 12:37 UTC, bogdan-rosianu approved these changes

2022-11-24 12:49 UTC, iulianpascalau approved these changes

2022-11-24 13:01 UTC, merged